// Generated by CoffeeScript 1.8.0
(function() {
  exports.Auth = {
    LOGIN: "https://secure.nicovideo.jp/secure/login?site=niconico",
    LOGOUT: "https://secure.nicovideo.jp/secure/logout",
    LOGINTEST: "http://live.nicovideo.jp/api/getplayerstatus/nsen/vocaloid"
  };

  exports.Live = {
    GET_PLAYER_STATUS: "http://live.nicovideo.jp/api/getplayerstatus/%s",
    GET_POSTKEY: "http://live.nicovideo.jp/api/getpostkey?thread=%s",
    NSEN_REQUEST: "http://live.nicovideo.jp/api/nsenrequest?v=%s&id=%s",
    NSEN_REQUEST_CANCEL: "http://live.nicovideo.jp/api/nsenrequest?v=%s&mode=cancel",
    NSEN_REQUEST_SYNC: "http://live.nicovideo.jp/api/nsenrequest?v=%s&mode=requesting",
    NSEN_GOOD: "http://ow.live.nicovideo.jp/api/nsengood?v=%s",
    NSEN_SKIP: "http://ow.live.nicovideo.jp/api/nsenskip?v=%s"
  };

  exports.Video = {
    GET_VIDEO_INFO: "http://ext.nicovideo.jp/api/getthumbinfo/%s"
  };

  exports.MyList = {
    FETCH_TOKEN: "http://www.nicovideo.jp/my/mylist",
    GET_GROUPS: "http://www.nicovideo.jp/api/mylistgroup/list",
    DefList: {
      LIST: "http://www.nicovideo.jp/api/deflist/list",
      ADD: "http://www.nicovideo.jp/api/deflist/add"
    },
    Normal: {
      LIST: "http://www.nicovideo.jp/api/mylist/list?group_id=%s",
      ADD: "http://www.nicovideo.jp/api/mylist/add"
    }
  };

}).call(this);
