// Generated by CoffeeScript 1.8.0

/*
 * このモジュールでは以下のイベントが発生します。
 *   "login"  : ニコニコ動画へログインした時に発生します。
 *   "logout" : ニコニコ動画からログアウトした時に発生します。
 */

(function() {
  var Nico, NicoAuthTicket, NicoLive, NicoMyList, NicoVideo;

  NicoAuthTicket = require("./api/NicoAuthTicket");

  NicoLive = require("./api/live/NicoLiveApi");

  NicoMyList = require("./api/mylist/NicoMyListApi");

  NicoVideo = require("./api/video/NicoVideoApi");

  Nico = (function() {
    Nico.prototype._ticket = null;

    Nico.prototype.live = null;

    Nico.prototype.mylist = null;

    Nico.prototype.video = null;

    function Nico(user, password) {
      this._ticket = new NicoAuthTicket(user, password);
      this.live = new NicoLive(this._ticket);
      this.mylist = new NicoMyList(this._ticket);
      this.video = new NicoVideo(this._ticket);
    }

    Nico.prototype.loginThen = function(resolved, rejected) {
      return this._ticket.loginThen(resolved, rejected);
    };

    return Nico;

  })();

  return Nico;


  /*
  Object.defineProperties module.exports,
      Auth:
          get: -> return NicoAuthApi
      Live:
          get: -> return NicoLiveApi
      Video:
          get: -> return NicoVideoApi
      MyList:
          get: -> return NicoMyListApi
   */

}).call(this);
