// Generated by CoffeeScript 1.8.0

/**
ニコニコ生放送APIラッパークラスエントランス
 */

(function() {
  var NicoLiveApi, NicoLiveInfo;

  NicoLiveInfo = require("./NicoLiveInfo");

  NicoLiveApi = (function() {

    /**
     * @param {NicoAuthTicket}   Authenticated NicoAuthTicket object
     */
    function NicoLiveApi(ticket) {
      this._ticket = ticket;
    }

    NicoLiveApi.prototype._getTicket = function() {
      return this._ticket;
    };


    /**
     * 指定された放送の情報を取得します。
     *
     * 番組情報が取得できればNicoLiveInfoオブジェクトとともにresolveされます。
     * 取得中にエラーが発生した場合、エラーメッセージとともにrejectされます。
     *
     * @param    {string}   liveId  放送ID
     * @return   {Promise} Promiseオブジェクト
     */

    NicoLiveApi.prototype.getLiveInfo = function(liveId) {
      if (typeof liveId !== "string" || liveId === "") {
        throw new Error("liveIdは文字列である必要があります。");
      }
      return new NicoLiveInfo(this, liveId);
    };


    /**
     * NicoLiveInfoオブジェクトからNsenChannelのインスタンスを取得します。
     * @param {NicoLiveInfo} obj
     * @return {NsenChannel}
     */

    return NicoLiveApi;

  })();

  return NicoLiveAPI;

}).call(this);
