// Generated by CoffeeScript 1.8.0

/**
 * ニコニコ動画のAPIへのアクセスを担当します。
 */

(function() {
  var NicoVideoApi, NicoVideoInfo;

  NicoVideoInfo = require("./NicoVideoInfo");

  NicoVideoApi = (function() {
    var getVideoInfo;

    NicoVideoApi.prototype._ticket = null;

    function NicoVideoApi(ticket) {
      this._ticket = ticket;
    }


    /**
     * 動画情報(NicoVideoInfo）を取得します。
     *
     * 動画情報が用意できれば取得したNicoVideoInfoオブジェクトと一緒にresolveされます。
     *
     * @param    {string}    movieId 情報を取得したい動画ID
     * @return   {Promise}
     */

    getVideoInfo = function(movieId) {
      var dfd, model;
      dfd = Promise.defer();
      model = new NicoVideoInfo(movieId);
      model.fetch().then(function() {
        dfd.resolve(model);
      }, function(msg) {
        dfd.reject(msg);
      });
      return dfd.promise;
    };

    return NicoVideoApi;

  })();

  module.exports = NicoVideoApi;

}).call(this);
